version: '3.1'

services:

  ###################################### httpd service with shared ~/public_http
  httpd:
    container_name: httpd
    image: llaumgui/httpd:2.4
    build:
      context: ../docker-images/httpd/2.4/
    restart: always
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ~/public_html:/var/www
     - ./volumes/conf/httpd/vhost.d:/usr/local/apache2/conf/vhost.d:ro
    ports:
     - "80:80"
     - "443:443"

  #################################### php-fpm service with shared ~/public_http
  php:
    container_name: php
    image: llaumgui/php:7.2-fpm
    build: 
      context: ../docker-images/php-fpm/7.2/
      args:
        DOCKER_PHP_ENABLE_APCU: 'on'
        DOCKER_PHP_ENABLE_COMPOSER: 'on'
        DOCKER_PHP_ENABLE_LDAP: 'off'
        DOCKER_PHP_ENABLE_MEMCACHED: 'on'
        DOCKER_PHP_ENABLE_MONGODB: 'off'
        DOCKER_PHP_ENABLE_MYSQL: 'on'
        DOCKER_PHP_ENABLE_POSTGRESQL: 'off'
        DOCKER_PHP_ENABLE_REDIS: 'off'
        DOCKER_PHP_ENABLE_SYMFONY: 'on'
        DOCKER_PHP_ENABLE_XDEBUG: 'on'
        DOCKER_USER_UID: 1000
        DOCKER_USER_GID: 1000
    restart: always
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ~/public_html:/var/www
     - ./volumes/log/php72:/var/log/php-fpm
    expose:
     - 9000
    depends_on:
     - httpd
     - mariadb
    links:
     - mariadb:database

  ### Start mariadb service from container.
  mariadb:
    container_name: mariadb
    image: mariadb:10
    restart: always
    env_file:
      - .env
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./volumes/data/mysql:/var/lib/mysql
    ports:
     - 127.0.0.1:3306:3306
