version: '3.1'

services:

  ### Start httpd service from container and share ~/public_http.
  httpd24:
    container_name: httpd24
    image: llaumgui/centos7-scl-httpd24
    build: 
      context: ../docker-images/httpd/2.4/
    restart: always
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ~/public_html:/var/www
     - ./volumes/conf/httpd24/vhost.d:/etc/httpd/vhost.d:ro
     - ./volumes/log/httpd24:/var/log/httpd24
    ports:
     - 80:80
    links:
     - php71:php

  ### Start php-fpm service from container.
  php71:
    container_name: php71
    image: llaumgui/php:7.1-fpm
    build: 
      context: ../docker-images/php-fpm/7.1/
      args:
        DOCKER_PHP_ENABLE_APCU: 'on'
        DOCKER_PHP_ENABLE_COMPOSER: 'on'
        DOCKER_PHP_ENABLE_LDAP: 'on'
        DOCKER_PHP_ENABLE_MEMCACHED: 'on'
        DOCKER_PHP_ENABLE_MONGODB: 'on'
        DOCKER_PHP_ENABLE_MYSQL: 'on'
        DOCKER_PHP_ENABLE_POSTGRESQL: 'on'
        DOCKER_PHP_ENABLE_REDIS: 'on'
        DOCKER_PHP_ENABLE_SYMFONY: 'on'
        DOCKER_PHP_ENABLE_XDEBUG: 'on'
    restart: always
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ~/public_html:/var/www
     - ./volumes/conf/php71/90-custom.ini:/usr/local/etc/php/conf.d/90-custom.ini:ro
     - ./volumes/log/php71:/var/log/php-fpm
    expose:
     - 9000
    links:
     - mariadb10:database
     - memcached:memcached

  ### Start mariadb service from container.
  mariadb10:
    container_name: mariadb10
    image: mariadb:10
    restart: always
    env_file:
      - .env
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./volumes/data/mysql:/var/lib/mysql
    ports:
     - 3306:3306

  # Start memcached service from container.
  memcached:
    container_name: memcached
    image: memcached
    volumes:
     - /etc/localtime:/etc/localtime:ro
    expose:
     - 11211
